<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Category\Handler\ProductsCategoryHandler::class => Category\Handler\ProductsCategoryHandlerFactory::class,
            Product\Handler\CreateHandler::class => Product\Handler\CreateHandlerFactory::class,
            Product\Handler\DeleteHandler::class => Product\Handler\DeleteHandlerFactory::class,
            Product\Handler\EditHandler::class => Product\Handler\EditHandlerFactory::class,
        ],
    ],
];
